import cors from "cors";
import express from "express";
import helmet from "helmet";
import morgan from "morgan";
import { ZodError } from "zod";
import { config } from "./config.js";
import { pool } from "./database.js";
import { AppError } from "./errors.js";
import { requestContext } from "./middleware/request-context.js";
import { appointmentsRouter } from "./routes/appointments.js";
import { auditRouter } from "./routes/audit.js";
import { authRouter } from "./routes/auth.js";
import { dashboardRouter } from "./routes/dashboard.js";
import { patientsRouter } from "./routes/patients.js";
import { pharmacyRouter } from "./routes/pharmacy.js";
import { visitsRouter } from "./routes/visits.js";
export const app = express();
app.set("trust proxy", 1); app.use(helmet()); app.use(cors({ origin: config.corsOrigin, credentials: true })); app.use(express.json({ limit: "100kb" })); app.use(requestContext); if (process.env.NODE_ENV !== "test") app.use(morgan("combined"));
app.get("/health", async (_req,res) => { try { await pool.query("SELECT 1"); res.json({ status:"ok", service:"healthos-backend" }); } catch { res.status(503).json({ status:"degraded", service:"healthos-backend" }); } });
app.use("/api/auth", authRouter); app.use("/api/dashboard", dashboardRouter); app.use("/api/patients", patientsRouter); app.use("/api/appointments", appointmentsRouter); app.use("/api/pharmacy", pharmacyRouter); app.use("/api/visits", visitsRouter); app.use("/api/audit", auditRouter);
app.use((_req,res) => res.status(404).json({ error:{ code:"NOT_FOUND", message:"Route not found" } }));
app.use((error: unknown,_req: express.Request,res: express.Response,_next: express.NextFunction) => { if (error instanceof ZodError) return res.status(400).json({ error:{ code:"VALIDATION_ERROR", message:"Invalid request payload", details:error.flatten() } }); if (error instanceof AppError) return res.status(error.status).json({ error:{ code:error.code, message:error.message, details:error.details } }); console.error(error); return res.status(500).json({ error:{ code:"INTERNAL_SERVER_ERROR", message:"Unexpected server error" } }); });
