-- Health-OS Africa workflow schema. Apply after database/init.sql.
ALTER TABLE patients ADD COLUMN IF NOT EXISTS allergies TEXT NOT NULL DEFAULT '';
ALTER TABLE patients ADD COLUMN IF NOT EXISTS chronic_conditions TEXT NOT NULL DEFAULT '';
ALTER TABLE medications ADD COLUMN IF NOT EXISTS drug_class VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE medications DROP CONSTRAINT IF EXISTS medications_qty_nonneg;
ALTER TABLE medications ADD CONSTRAINT medications_qty_nonneg CHECK (quantity_on_hand >= 0);
CREATE TABLE IF NOT EXISTS tenant_counters (tenant_id UUID NOT NULL REFERENCES tenants(id), name VARCHAR(50) NOT NULL, value INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (tenant_id,name));
INSERT INTO tenant_counters (tenant_id,name,value) SELECT tenant_id,'patient',count(*) FROM patients GROUP BY tenant_id ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS visits (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id), clinic_id UUID NOT NULL REFERENCES clinics(id), patient_id UUID NOT NULL REFERENCES patients(id), stage VARCHAR(20) NOT NULL DEFAULT 'TRIAGE' CHECK(stage IN ('TRIAGE','CONSULT','PHARMACY','DONE')), priority VARCHAR(20) NOT NULL DEFAULT 'ROUTINE' CHECK(priority IN ('ROUTINE','URGENT','CRITICAL')), complaint TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS uq_visits_active_patient ON visits(patient_id) WHERE stage <> 'DONE';
CREATE INDEX IF NOT EXISTS idx_visits_queue ON visits(tenant_id,clinic_id,stage,created_at);
ALTER TABLE triage_records ADD COLUMN IF NOT EXISTS visit_id UUID REFERENCES visits(id); ALTER TABLE triage_records ADD COLUMN IF NOT EXISTS respiratory_rate INTEGER; ALTER TABLE triage_records ADD COLUMN IF NOT EXISTS triaged_by UUID REFERENCES users(id); ALTER TABLE consultations ADD COLUMN IF NOT EXISTS visit_id UUID REFERENCES visits(id);
CREATE TABLE IF NOT EXISTS prescriptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id), clinic_id UUID NOT NULL REFERENCES clinics(id), visit_id UUID NOT NULL REFERENCES visits(id), consultation_id UUID NOT NULL REFERENCES consultations(id), medication_id UUID NOT NULL REFERENCES medications(id), quantity INTEGER NOT NULL CHECK(quantity > 0), status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','DISPENSED')), dispensed_by UUID REFERENCES users(id), dispensed_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS stock_movements (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id UUID NOT NULL REFERENCES tenants(id), medication_id UUID NOT NULL REFERENCES medications(id), delta INTEGER NOT NULL, reason VARCHAR(50) NOT NULL, visit_id UUID REFERENCES visits(id), user_id UUID REFERENCES users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT now());
UPDATE medications SET drug_class='penicillin' WHERE lower(generic_name)='amoxicillin';
INSERT INTO medications (tenant_id,generic_name,brand_name,strength,quantity_on_hand,reorder_threshold,expiry_date,drug_class) SELECT '11111111-1111-1111-1111-111111111111',v.g,v.b,v.s,v.q,v.t,v.e::date,'' FROM (VALUES ('Salbutamol','Ventolin','100mcg inhaler',18,10,'2027-03-31'),('Amlodipine','Norvasc','5mg',60,50,'2027-09-30'),('Oral rehydration salts','ORS','sachet',90,30,'2027-12-31')) v(g,b,s,q,t,e) WHERE NOT EXISTS (SELECT 1 FROM medications m WHERE m.generic_name=v.g AND m.tenant_id='11111111-1111-1111-1111-111111111111');
INSERT INTO users (tenant_id,clinic_id,email,password_hash,first_name,last_name,role) SELECT '11111111-1111-1111-1111-111111111111','22222222-2222-2222-2222-222222222222',v.e,a.password_hash,v.f,'Demo',v.r FROM (VALUES ('reception@healthos.test','Rita','RECEPTIONIST'),('nurse@healthos.test','Nomsa','NURSE'),('doctor@healthos.test','Dumisani','DOCTOR'),('pharmacist@healthos.test','Pule','PHARMACIST')) v(e,f,r),(SELECT password_hash FROM users WHERE email='admin@healthos.test' LIMIT 1) a ON CONFLICT(tenant_id,email) DO NOTHING;
