import rateLimit from "express-rate-limit";
import bcrypt from "bcryptjs";
import { Router } from "express";
import jwt from "jsonwebtoken";
import { z } from "zod";
import { config } from "../config.js";
import { query } from "../database.js";
import { ah } from "../errors.js";
import { audit } from "../services/audit.js";
const schema = z.object({ email: z.string().email(), password: z.string().min(8), tenantId: z.string().uuid().optional() });
export const authRouter = Router();
const limiter = rateLimit({ windowMs: 60_000, limit: config.loginRateLimit, standardHeaders: true, legacyHeaders: false, message: { error: { code: "RATE_LIMITED", message: "Too many login attempts. Try again in a minute." } } });
authRouter.post("/login", limiter, ah(async (req, res) => { const b = schema.parse(req.body); const r = await query<any>(`SELECT id,tenant_id,clinic_id,email,password_hash,first_name,last_name,role,active FROM users WHERE lower(email)=lower($1) AND ($2::uuid IS NULL OR tenant_id=$2) ORDER BY created_at LIMIT 1`, [b.email, b.tenantId ?? null]); const u = r.rows[0]; const valid = u?.active ? await bcrypt.compare(b.password, u.password_hash) : false; if (!u || !valid) { await audit(undefined,"LOGIN_FAILED","User",undefined,{ email: b.email }); return res.status(401).json({ error: { code: "INVALID_CREDENTIALS", message: "Invalid email or password" } }); } const accessToken = jwt.sign({ sub:u.id, tenant_id:u.tenant_id, clinic_id:u.clinic_id, email:u.email, role:u.role }, config.jwtSecret, { expiresIn:"8h", algorithm:"HS256" }); await audit({ id:u.id, tenantId:u.tenant_id, clinicId:u.clinic_id, email:u.email, role:u.role },"LOGIN_SUCCESS","User",u.id); res.json({ data: { accessToken, user: { id:u.id, tenantId:u.tenant_id, clinicId:u.clinic_id, email:u.email, firstName:u.first_name, lastName:u.last_name, role:u.role } } }); }));
