"use client";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "../../components/AppShell";
import { apiFetch } from "../../lib/api";
type Patient = { id: string; patient_number: string; first_name: string; last_name: string; gender: string; phone: string | null; allergies: string | null };
export default function PatientsPage() {
  const [patients, setPatients] = useState<Patient[]>([]); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [form, setForm] = useState({ firstName: "", lastName: "", phone: "", gender: "UNKNOWN", allergies: "" });
  async function load() { setPatients(await apiFetch<Patient[]>("/api/patients")); }
  useEffect(() => { load().catch((err) => setError(err.message)); }, []);
  async function checkIn(id: string) { setError(""); setNotice(""); try { await apiFetch("/api/visits/check-in", { method: "POST", body: JSON.stringify({ patientId: id }) }); setNotice("Patient checked in and added to triage queue."); } catch (err) { setError(err instanceof Error ? err.message : "Unable to check in patient"); } }
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); try { await apiFetch("/api/patients", { method: "POST", body: JSON.stringify(form) }); setForm({ firstName: "", lastName: "", phone: "", gender: "UNKNOWN", allergies: "" }); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to create patient"); } }
  return <AppShell><section className="grid columns"><div className="panel"><h2>Patients</h2>{error && <div className="error">{error}</div>}{notice && <div className="notice">{notice}</div>}<table className="table"><thead><tr><th>Patient No.</th><th>Name</th><th>Gender</th><th>Phone</th><th>Allergies</th><th /></tr></thead><tbody>{patients.map((patient) => <tr key={patient.id}><td>{patient.patient_number}</td><td>{patient.first_name} {patient.last_name}</td><td>{patient.gender}</td><td>{patient.phone || "-"}</td><td>{patient.allergies || "-"}</td><td><button className="button secondary" onClick={() => checkIn(patient.id)} type="button">Check in</button></td></tr>)}</tbody></table></div><div className="panel"><h2>Register Patient</h2><form className="form" onSubmit={submit}><div className="field"><label htmlFor="firstName">First name</label><input id="firstName" onChange={(e) => setForm({ ...form, firstName: e.target.value })} required value={form.firstName} /></div><div className="field"><label htmlFor="lastName">Last name</label><input id="lastName" onChange={(e) => setForm({ ...form, lastName: e.target.value })} required value={form.lastName} /></div><div className="field"><label htmlFor="phone">Phone</label><input id="phone" onChange={(e) => setForm({ ...form, phone: e.target.value })} value={form.phone} /></div><div className="field"><label htmlFor="gender">Gender</label><select id="gender" onChange={(e) => setForm({ ...form, gender: e.target.value })} value={form.gender}><option value="UNKNOWN">Unknown</option><option value="FEMALE">Female</option><option value="MALE">Male</option><option value="OTHER">Other</option></select></div><div className="field"><label htmlFor="allergies">Allergies</label><input id="allergies" onChange={(e) => setForm({ ...form, allergies: e.target.value })} value={form.allergies} /></div><button className="button" type="submit">Create patient</button></form></div></section></AppShell>;
}
